//POST http://localhost:3001/employees

# @name token
POST https://login.microsoftonline.com/508e46f2-cd47-4e73-9d05-bede96f92469/oauth2/token
Content-Type: application/x-www-form-urlencoded

grant_type=client_credentials&client_id=932faa09-5bb8-41cd-a18f-5362518f37fe&client_secret=xxxxO&scope=api://6fd66934-cf5b-453a-b580-ee8ab28ca10f/default

###
@ati-portal-api-token={{token.response.body.access_token}}

###

POST https://ati-portal-api--0000004.wittywater-96695c96.eastus.azurecontainerapps.io/employees
###
POST http://localhost:3001/employees
Content-Type: application/json

{
  "firstName": "Vishnuvardhan",
  "lastName": "Sankoti",
  "email": "shankotai@hotmail.com",
  "phone": "+13142017054",
  "department": "Engineering",
  "position": "Principal Engineer",
  "manager": "Seshu Devrapally",
  "hireDate": "2024-01-15",
  "employeeId": "EMP001",
  "address": "2065 Cannon Heights Dr",
  "addressLine2": "Apt 6",
  "city": "Chesterfield",
  "state": "MO",
  "zipCode": "63017",
  "emergencyContact": "Srividya",
  "emergencyPhone": "+12134369112",
  "skills": ["JavaScript", "TypeScript", "React", "Node.js", "NestJS"],
  "comment": "Senior developer with 18 years of experience"
}
###
{
    "firstName": "Srividya",
    "lastName": "Ramamoorthy",
    "role": "HR",
    "emailId": "vidya.rama@atiglobalservices.com",
    "addressLine1": "2060 Cannon Heights Dr",
    "addressLine2": "Apt 6",
    "city": "Chesterfield",
    "state": "MO",
    "zipCode": "63017",
    "phoneNumber": "+13142017054",
    "isActive": true,
    "hireDate": "2022-03-31T00:00:00.000Z"

}